<div style="text-align: right"> CS824 - Lab 6a (2022) </div>

# Basic array operations (in *NumPy*)

I realise that people are coming to this week's labs with different levels of exposure to the **array** data type in Python, and I'm unsure as to how much practice you got with arrays in the general Python programming introductions. 

If you feel comfortable with these basics then you might want to move quickly through these or just tackle the 'extra' exercise at **Exercise 6a5** towards the end of this notebook to check your understanding. You may also want to jump straight on to their application to the case of vector algebra (**Lab_6b**), from where you should quickly be able to progress to the exercises on matrices (**Lab_6c** and **Lab_6d**)...


## Creating and working with *NumPy* arrays

In addition to being the way in which we work with vectors (and indeed matrices and tensors!) the NumPy `array` class is at the heart of almost **ALL** data manipulation in Python. For example, `Pandas` is built on top of the notion of NumPy arrays. 

In this first section we will (mostly) work with 1-dimensional arrays, representing vectors, but this class supports the general-purpose `n-dimensional` array which is used in many sorts of numerical computing - including many ML algorithms. The notion of a `matrix` is really only required in more classic computations specific to linear algebra, with matrix objects being limited to exactly **two** dimensions. While the concepts of matrix multiplication and other transformations from linear algebra are of course important, the mathematical objects of matrices can (and arguably, *should*) be thought of as simply 2-dimensional arrays - which will avoid the need to switch between the 'currencies' of `array` and `matrix`. Indeed it is proposed that the `matrix` object type may soon be depricated from the official Python language. If interested you read more in the NumPy developer's post on - [array or matrix - Which should I use?](https://numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use)


## Attributes of arrays

Some of the material below may feel like 'dry manipulation' but geting familar with how to process different types of arrays in Python is really important (and helps with things like figuring out how best to work with `Pandas` data sets)...  so try to bear with me and/or skim through this quickly if it seems obvious.


In [1]:
# As noted we can create arrays of 1-D (vectors), 2-D (matrices) or basically any dimension (which allows
# us to work with 'tensors').  Let's create three different arrays, filling their values with random numbers...

import numpy as np
np.random.seed(9)              # just so that we all get the same array contents, if we want to compare outputs

a1 = np.random.randint(1, 7, size=20)             # 1-D array (e.g. this might repesent 20 throws of a die)

# We use the fact that the `randint` function returns an array to allocate this to our variable.
# If we use more than one element in the `size` parameter then we will get an extra dimension 
# for each additional element with as many members are specified in that dimension of the 'size' parameter.

a2 = np.random.randint(1, 7, size=(2, 5))         # 2-D array (maybe two different people making 5 throws each)
a3 = np.random.randint(1, 7, size=(3, 2, 8))      # 3-D array (who knows?!) 
                                                  # (Maybe 3 instances of a 2-player game involving 8 throws each?)


It's easy to lose track of which arrays are of which size/structure so there are a number of array attributes that you can query. These include `ndim` (the # of dimension), `shape` (the # of elements in each dimension) and `size` (the overall number of elements in the whole array - often not *that* useful).


In [2]:
# So we could confirm that 'a2' is a 2-D array and contains a total of 10 elements.

print("Number of dimensions in a2: ", a2.ndim)
print("Structure of a2: ", a2.shape)
print("Total number of elements in a2: ", a2.size)
print(a2)


Number of dimensions in a2:  2
Structure of a2:  (2, 5)
Total number of elements in a2:  10
[[1 3 1 6 3]
 [5 1 5 3 1]]


## Exercise 6a1

Use the `ndim`, `shape` and `size` attributes to check out the details of the other two arrays (a1 and a3) that you have created.


You may remember that you can use the 'magic' command `%whos` to see a list of variables defined in the current scope. You can add a suffix of 'type' to only see the details of variables of a given type (i.e. here `ndarray`).

You can also use the command "?" to bring back information on a given variable - so for example typing "a1?" below will bring up the 20 'die throw' results in our array as well as a bunch of other information.


In [3]:
print("Number of dimensions in a1: ", a1.ndim)
print("Structure of a1: ", a1.shape)
print("Total number of elements in a1: ", a1.size)
print(a1)

Number of dimensions in a1:  1
Structure of a1:  (20,)
Total number of elements in a1:  20
[5 6 1 4 6 2 5 4 1 3 2 1 6 4 2 6 5 1 5 4]


In [4]:
print("Number of dimensions in a3: ", a3.ndim)
print("Structure of a3: ", a3.shape)
print("Total number of elements in a3: ", a3.size)
print(a3)

Number of dimensions in a3:  3
Structure of a3:  (3, 2, 8)
Total number of elements in a3:  48
[[[2 1 4 4 6 4 2 1]
  [1 2 1 6 4 3 2 6]]

 [[6 5 3 3 1 5 6 4]
  [5 3 1 3 1 1 5 6]]

 [[5 1 4 1 5 4 1 1]
  [2 3 6 4 5 4 6 3]]]


## Exercise 6a2

Use the `%whos` command, with its type suffix (`ndarray`) to list details of the three arrays that we have created.

Take a look at what using `?` after a variable name results in...  (Arguably not as useful as you might think/hope once you get to more complex objects.)


In [5]:
%whos

Variable   Type       Data/Info
-------------------------------
a1         ndarray    20: 20 elems, type `int32`, 80 bytes
a2         ndarray    2x5: 10 elems, type `int32`, 40 bytes
a3         ndarray    3x2x8: 48 elems, type `int32`, 192 bytes
np         module     <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
os         module     <module 'os' from 'c:\\Us<...>envs\\myenv\\lib\\os.py'>
sys        module     <module 'sys' (built-in)>


## Using array indexes to access single elements

Often we wish to work with a single element (or 'slice' - see next section) of the array at a time...  as such we need to feel confident about accessing elements of an array...


In [6]:
a1

array([5, 6, 1, 4, 6, 2, 5, 4, 1, 3, 2, 1, 6, 4, 2, 6, 5, 1, 5, 4])

In [7]:
# Remember that the array index (or indices) start from 0...
a1[0]

5

In [8]:
# So to retrieve the 8th element...
a1[7]

4

In [9]:
# We can also use negative indices to select from the end of an array.
a1[-1]

4

In [10]:
# Though, slightly confusingly, there is no "-0"th item when counting backwards...
# i.e. the 4th last element has an index of -4, while the 4th item has an index of +3  :-(
a1[-4]

5

When we are dealing with an array that is larger than a single dimension (e.g. a matrix) then we can access specific values by using a comma-separated tuple (a pair in the case of a matrix, AKA "2-D array") of indices.


In [11]:
a2

array([[1, 3, 1, 6, 3],
       [5, 1, 5, 3, 1]])

In [12]:
# We can access the first throw by the first player ('top-left' element) as follows -
a2[0, 0]

1

## Exercise 6a3

Use the appropriate tuple (pair) of indices on `a2` to select:
 - the fourth throw of the first player;
 - the second last throw of the second player (maybe look at a couple of ways to refer to this same element, including the use of a 'negative' index)


In [13]:
a2[0, 3]

6

In [14]:
a2[1, -2]

3

You can also use these types of indices/tuples to identify element(s) that you wish to update.

In [15]:
a2[1,4] = 6

In [16]:
a2

array([[1, 3, 1, 6, 3],
       [5, 1, 5, 3, 6]])

But remember that, unlike lists, NumPy `array` objects have a fixed type.  In our example all elements must be of type integer (strictly `int32`), so if you try to insert a non-integer value it will be 'silently' truncated to the nearest integer (i.e. you will **not** get any sort of 'warning' message that this has taken place).

In [17]:
a2[1,4] = 25/3         # check what happpens when you try this assignment

In [18]:
a2

array([[1, 3, 1, 6, 3],
       [5, 1, 5, 3, 8]])

In [19]:
a2[1, 4] = 'a'

ValueError: invalid literal for int() with base 10: 'a'

## 'Slices' of arrays - accessing subsets of array elements

Again you may be familar with this from having used `Pandas` but make sure that both simple and more complex array slicing feels comfortable to you, as you will often wish to work with a sub-set of values...

The 'slicing' syntax involves one or more colon (`:`) characters within the array reference. If we have an ndarray `A` then -
> `A[start:stop:step]`

specifies where we wish to start/stop the slice and then whether we wish all the values (step = 1) or just every `step`-th elememt. The defaults are `start=0`, `stop=size of given dimension` and `step=1`. The same syntax works for arrays of one or many dimension - but it can take a while to get your head around the syntax for >1 dimension!


In [20]:
a4 = np.arange(15)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
a4[:3]         # first three elements

array([0, 1, 2])

In [22]:
a4[12:]         # elements from after index 12  (more intuitive below)

array([12, 13, 14])

In [23]:
a4[-3:]         # last three elements

array([12, 13, 14])

In [24]:
a4[::-1]        # Reversing the array

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [25]:
a4[:5:-1]       # Reversing till the specifix index

array([14, 13, 12, 11, 10,  9,  8,  7,  6])

In [26]:
a4[12:3:-1]     # reversing a specific sub-array from the array

array([12, 11, 10,  9,  8,  7,  6,  5,  4])

In [27]:
a4[4:8]         # a sub-set of values from the middle of the array

array([4, 5, 6, 7])

When the `step` value is negative the default for `start` and `stop` are switched around - i.e. the default for `start` becomes the last element and the default for `stop` the first.  This is handy when referring to an array in its reverse order, but can also be confusing at first...


In [28]:
a4[::3]         # every third value

array([ 0,  3,  6,  9, 12])

In [29]:
a4[2::3]         # every third value, starting from the third entry

array([ 2,  5,  8, 11, 14])

In [30]:
a4[::-1]         # all elements in reverse order

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [31]:
a4[9::-2]         # reversed list of every second element from index 9

array([9, 7, 5, 3, 1])

When dealing with >1 dimension you will typically need > one group of `:` (separated by commas) for each dimension that you wish to slice...


In [32]:
a2

array([[1, 3, 1, 6, 3],
       [5, 1, 5, 3, 8]])

In [33]:
a2[:, 3:4]         # all entries from the third column

array([[6],
       [3]])

In [34]:
a2[:2, 3:4]         # first two rows from the third column, which happens to be the same as above

array([[6],
       [3]])

In [35]:
a2[:1, 3:4]         # just the first row from the third column

array([[6]])

In [36]:
a2[::2, :]         # every other row and all columns

array([[1, 3, 1, 6, 3]])

In [37]:
a2[::-1, ::-1]         # you can also reverse the rows and columns at the same time

array([[8, 3, 5, 1, 5],
       [3, 6, 1, 3, 1]])

In [38]:
a2[::1, ::-1]       # reversing the column only, notice that only the matrix is flipped horizontally

array([[3, 6, 1, 3, 1],
       [8, 3, 5, 1, 5]])

In [39]:
a2[::-1, ::1]       # reversing the rows only, notice that the matrix is flipped vertically

array([[5, 1, 5, 3, 8],
       [1, 3, 1, 6, 3]])

Quite often you may wish to select a single row (or single column) of a larger array. This is done using an **'empty slice'**...


In [40]:
a2[0, :]            # the first row of a2

array([1, 3, 1, 6, 3])

In [41]:
a2[:, 0]            # the first column of a2. Note that what is returned is a 1-D array and as such there is only one
                    # row, which used to be the column...  (Arrays can take a while to get your head around!)

array([1, 5])

In [42]:
print(a2[1])        # in the case of accessing rows you will often see the 'empty slice' left out of the statement

[5 1 5 3 8]


## Exercise 6a4

Using the 3-dimensional array (a3) we created earlier find the following:
 - all the die outcomes involved in the first game;
 - the throws made by the second player in the third game;
 - the second-last throw made by the first player in the final game;


In [43]:
a3

array([[[2, 1, 4, 4, 6, 4, 2, 1],
        [1, 2, 1, 6, 4, 3, 2, 6]],

       [[6, 5, 3, 3, 1, 5, 6, 4],
        [5, 3, 1, 3, 1, 1, 5, 6]],

       [[5, 1, 4, 1, 5, 4, 1, 1],
        [2, 3, 6, 4, 5, 4, 6, 3]]])

In [44]:
a3[0, :, :]     # all the die outcomes involved in the first game;

array([[2, 1, 4, 4, 6, 4, 2, 1],
       [1, 2, 1, 6, 4, 3, 2, 6]])

In [45]:
a3[2, 1, :]     # the throws made by the second player in the third game;

array([2, 3, 6, 4, 5, 4, 6, 3])

In [46]:
a3[2:, 0:1, 6:7]    # the second-last throw made by the first player in the final game;

array([[[1]]])

## Exercise 6a5 ('extra' challenge)

This 'extra' element is really just for those who have already used arrays a fair bit in Python - i.e. you skimming through the material above as it felt very basic to you. If you are in that catergory you might want to try the little exercise below; but otherwise please move on with the rest of the material (you can always come back to this if you have a bit of time at the end of the lab).

If you plan to tackle the exercise below you will need to check out the NumPy `sum` function (and maybe others).
  - Rules_A: Assume that the winner of each game is the player whose total over the 8 throws is highest;
  - Rules_B: Assume that you get one point if on a given roll you score higher than your opponent and that the player with the most points after 8 rolls wins;
 - for either set of rules your function should be able to take a set of games and say which player was the overall winner (i.e. most games won).

Rather than just using the 3 games we stored in `a3` you could generate a scenario of, say, 50 random games and explore: does each set of rules tend to result in a similar set of outcomes?; which set of rules results in more drawn games?; etc.


In [47]:
a3

array([[[2, 1, 4, 4, 6, 4, 2, 1],
        [1, 2, 1, 6, 4, 3, 2, 6]],

       [[6, 5, 3, 3, 1, 5, 6, 4],
        [5, 3, 1, 3, 1, 1, 5, 6]],

       [[5, 1, 4, 1, 5, 4, 1, 1],
        [2, 3, 6, 4, 5, 4, 6, 3]]])

In [48]:
print("Sum of arr(axis = 0) : ", np.sum(a3, axis = 0))
print("Sum of arr(axis = 1) : ", np.sum(a3, axis = 1))
print("Sum of arr(axis = 2) : ", np.sum(a3, axis = 2))

Sum of arr(axis = 0) :  [[13  7 11  8 12 13  9  6]
 [ 8  8  8 13 10  8 13 15]]
Sum of arr(axis = 1) :  [[ 3  3  5 10 10  7  4  7]
 [11  8  4  6  2  6 11 10]
 [ 7  4 10  5 10  8  7  4]]
Sum of arr(axis = 2) :  [[24 25]
 [33 25]
 [22 33]]


In [ ]:
# Total scores of eachplayers in each game
total_score = np.sum(a3, axis=2)
for game in total_score:
    for i_scores in game:
        

(3, 2)


## 'Sub-arrays' are views (NOT copies) of the array they relate to

This can be VERY confusing at first!  When you take a 'slice' of an array it is a *view* rather than a *copy* of the underlying data. This is different from Python lists, where taking a slice from a list will give you a copy of that portion of the list...  this is NOT the case (by default) for arrays.


In [ ]:
print(a2)             # let's remind ourselves of the contents

In [ ]:
sub_a2 = a2[:,1:4]    # take a 2X3 sub-array from a2 (both rows from the 2nd to the 4th column)
print(sub_a2)

In [ ]:
sub_a2[0, 0] = 55     # alter one value in the sub-array and then look back at the original
print(sub_a2)

In [ ]:
print(a2)            # notice that the corresponding entry has been updated

This can be very useful when processing lots of data as it means that you don't need to make copies, operate on sub-sets of data, and then paste the results back into the main array (the changes will already have been made).

Of course you also need to be aware the this IS the default behaviour!  Also, it is sometimes the case that you actually *want* a copy of the data and do not want to alter the original values. To do this you need to use the `copy()` method. 


## Exercise 6a6
Repeat the operations above but this time make a change only to the `sub_a2_copy` object...  check that when you modified the sub-array on this occasion that it did NOT alter the array to which the sub-array was referring.


In [ ]:
print(a2)                        # check contents of our existing a2

There are many other `ndarray` operations, including:
 - reshaping
 - concatenation
 - splitting
 - etc
 
For some of these there are also 'special' versions of the operation for 2-D arrays (dating back to the 'special' treatment of the `matrix` data type), so that the more generic `np.concatenate` has the `np.vstack` and `np.hstack` when you want to 'stack' (~ `concatenate`) arrays in a vertical or horizontal direction.

We don't really have time to get into these (or other) array functions here, but we may encounter some as we move more explicitly to think about how to use arrays to implement vector algebra. (**Lab_6b**)
