<div style="text-align: right"> CS824 - Lab 6d (2022) </div>

# Using matrices to transform vectors

There are a few 'standard' transformations that are illustrated below for the 2-D case - i.e. vectors in (i, j) space operated on by a {2 x 2} matrix. You can try these transformatons out with vectors of your choosing.  Probably the best way to appreciate the effect of each transformation would be to view these graphically, but as you saw in an earlier section of this lab I have not yet found a quick / easy way in Python to do this - so if you find one **please** share it with the class on the *forum*...

However, there are some good resources on-line that let you explore some of this. By far the best on-line material I have found is the *3Blue1Brown* set of videos from Grant Sanderson. I have suggested a couple of those as part of this week's mini-lectures, but his whole series on the **Essence of linear algebra** (all 15 parts!) will be well worth putting aside to watch at some point if some of this still feels like 'magic' to you (hint: it's not!). 

As noted on *MyPlace*, in the context of this lab the 3rd video in that series [Linear Transformations and Matrices](https://www.youtube.com/watch?v=kYB8IZa5AuE&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=3), is of particular relevance.

You could watch segments, then pause the video and see whether you can replicate some of the operations in Python - though the nice visualisations that Grant generates often makes it more intuitive just to watch those.


In [1]:
# The 'Identity' matrix

import numpy as np
from numpy import linalg as LA

# Let's create a few vectors (as column vectors) to work with...
v1 = np.array([[6],
               [2]])

v2 = np.array([[1],
               [4]])

mat_Identity = np.array([[1, 0],
               [0, 1]])

# For the purposes to discussion below we will refer to the [2x2] matrices that we will be restricting ourselves to
# in terms of the elements:
# [a, b]
# [c, d]
# i.e. in this first example, a=1, b=0, etc.

v1t = mat_Identity @ v1
v2t = mat_Identity @ v2

print(v1t)
print(v2t)


[[6]
 [2]]
[[1]
 [4]]


**Identity matrix**

This is a special case of the more general 'scalar' matrix - and, perhaps not surprisingly, it doesn't do anything!!

In the more general case, mutiplying by a **_scalar matrix_** will alter the size by `a` in the i-direction and `d` in the j-direction. 


In [12]:
# Scalar matrices

mat_Scalar = np.array([[3, 0],
               [0, 3]])

v1t = mat_Scalar @ v1
v2t = mat_Scalar @ v2

print(LA.norm(v1))
print(LA.norm(v1t))

print(LA.norm(v2))
print(LA.norm(v2t))

print(v1)
print(v2)
print(v1t)
print(v2t)


6.324555320336759
18.973665961010276
4.123105625617661
12.36931687685298
[[6]
 [2]]
[[1]
 [4]]
[[18]
 [ 6]]
[[ 3]
 [12]]


We see that in this case the i and j components are both 'stretched' by a factor of 3. As a consequence the whole area (if we thought of the vector as representing a bounded box from the origin) is increased by a factor of 9 (i.e. in the case of the second vector from an 'area' of 4 to an area of 36.

Indeed the `Determinant` of a matrix (in the case of a 2x2 this is simply = ad - bc) tells you by how much the area bounded by the vector (or set of vectors, for a more complicated shape) will be increased/decreased, i.e.: 

 - if (a * d) `>` 1  ===> 'stretch'
 - if (a * d) `<` 1  ===> 'shrink'


## Exercise 6d1

Of course matrices do not need to be 'symmetic', as in the case of **identity** or **scalar** matrices.

 - Can you find a transform matrix that would expand the 'area' bounded by a vector in 2-D space by a factor of 4?
 - What about if you wish to reduce the length of vectors by 1/2 but keep the same orientation?
 - How about increasing the 'area' by a factor of 2 but also 'flipping' the vector about the y-axis?
 

In [9]:
print(v1)
print(v2)
mat_Scalar = np.array([[2, 0],
               [0, 2]])

v1t_4 = mat_Scalar @ v1
v2t_4 = mat_Scalar @ v2

print(v1t_4)
print(v2t_4)

[[6]
 [2]]
[[1]
 [4]]
[[12]
 [ 4]]
[[2]
 [8]]


In [10]:
# Let's create a few vectors (as column vectors) to work with...
v1_h = np.array([[3],
               [1]])

v2_h = np.array([[1/2],
               [2]])

print(v1_h)
print(v2_h)
mat_Scalar = np.array([[2, 0],
               [0, 2]])

v1t_4_h = mat_Scalar @ v1_h
v2t_4_h = mat_Scalar @ v2_h

print(v1t_4_h)
print(v2t_4_h)

[[3]
 [1]]
[[0.5]
 [2. ]]
[[6]
 [2]]
[[1.]
 [4.]]


In [19]:
print(v1)
print(v2)
mat_Scalar = np.array([[1.41, 0],
               [0, 1.41]])

v1t_4 = mat_Scalar @ v1
v2t_4 = mat_Scalar @ v2

print(v1t_4)
print(np.flip(v1t_4))
print(v2t_4)
print(np.flip(v2t_4))

[[6]
 [2]]
[[1]
 [4]]
[[8.46]
 [2.82]]
[[2.82]
 [8.46]]
[[1.41]
 [5.64]]
[[5.64]
 [1.41]]


### Inversion matrix

You can invert a vertor by mupliplying by the 'negative' Identity...


In [24]:
# Inversion matrix

mat_Invert = np.array([[-1, 0],
               [0, -1]])

v1t = mat_Invert @ v1
v2t = mat_Invert @ v2

print(v1t)
print(v2t)


[[-6]
 [-2]]
[[-1]
 [-4]]


## Exercise 6d2

You can of course also stretch or shrink, while inverting, by using values other than -1

 - Invert these vectors while also increasing them by a factor of 2 in the i-direction and 4 in the j-direction
 - What about if you wanted to invert AND reduce their lengths by 1/4?
 

### Flipping / Mirroring

You can 'mirror' in the y-axis by setting `a` = -1 and keeping 0 values in postitions `b` and `c`...  You can also mirror in the x-axis, as well as in the +45 and -45 degree lines of symmetry...  


## Exercise 6d3

 - See whether you can figure out the matrix required to perform a mirroring in the x-axis.

 - Next try to reflect thru the line at 45 degrees to the origin - i.e. {6,2} should end up at {2, 6}, etc. Then try to find the 'opposite' 45 degree reflection.

(Hint: In these last cases you need to work with the `b` and `c` element, and set `a` and `d` to zero.)  


### Rotating

For any given angle `theta` you can carry out a rotation of `theta` radians (by default) by using the following matrix:

(`Cos theta`,  `Sin theta`
<br> `-Sin theta`, `Cos theta`)
 

## Exercise 6d4

Create a little function that takes in the value of an angle `theta` and a vector, and returns the components of the vector after these have been rotated about angle `theta`.


### Performing a 'shear'

This is perhaps the most difficult to appreciate without looking at graphical output. (Take another look at the *3Blue1Brown* video suggested if you want to get more of a 'visual' feel for this transformation.)

Using the simple matrix below you can 'shift' a 1x1 square area into a 1x1 trapezoid, still with length 1 in the `i` direction, but 'sheared' along it's y-axis.

<br>(1, 1
<br> 0, 1)

And if you alter these 1 values to others then you will end up with different types of shear...



Essentially these are **all** of the types of transformations that a 2x2 matrix can exert on a vector in 2-D space; thought you can of course use combinations of these to generate more 'interesting' outcomes... 

#### There are also transforms that will result in 2-D space being reduced to a line...  see below, when the `determinant` = 0. (Or in the case of 3-D space, will result in that 3-D volume being mapped into a single plane.)


## Exercise 6d5

 - Experiment a little with the transformations of different matrices and see how the resulting vectors are essentially made up of the components that we have noted above. (The whole point of **linear** combinations is that they cannot by definition warp/bend space in more that a certain number of pre-defined ways...  and these limitations also hold for the 3-D and higher dimensional spaces - it just gets a bit harder to visualise!)
 
 - There is one other special case that is worth noting, which is when then `determinant` of the matrix = 0. In this case the resulting 'area' of a set of vectors is reduced to zero - i.e. the results lie on a straight line. Experiment with some vectors that have the `deterimnant` (`a * d` - `b * c`) equal to zero.
 

### That's about it for a very basic intro to vectors and matrices...

If you skipped over it, you may wish to go back to **Exercise 6a5** and see whether you now feel a bit more confident to tackle that little task.
